### PR TITLE
Update script.user.js

### PR DESCRIPTION
**Pull request by zek0faws**

### CODE REVIEW

**Comment by franckentien** [comment]
looks good for me

**Comment by quiquelhappy** [comment]
don't merge @YisusOnDev

**Review by tchenu — APPROVED** [review]

**Comment by JazzDesign** [comment]
I only see the French people crying HAHAHAHAH

**Comment by zek0faws** [comment]
BIP BOUP CANT TALK IM A ROBOT @JazzDesign @quiquelhappy

**Pull request closed without merging**
