### PR TITLE
Update script.user.js

### PR DESCRIPTION
**Pull request by Piervers**
That's cheating dude

### CODE REVIEW

**Comment by lecrisma** [comment]
the code does not belong to the creator, it belongs to a friend of mine who created it.

**Comment by EyLuismi** [comment]
> 

The original author is on the second line of the file dude

**Comment by Piervers** [comment]
> > 
> 
> The original author is on the second line of the file dude

Still, he is the one who modified it and who make it shareable. If he deleted the json, the script will stop working. Easy and simple

**Comment by EyLuismi** [comment]
> Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple

That's correct, but... Why? xD

**Comment by Piervers** [comment]
> > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> 
> That's correct, but... Why? xD

Why what ? Why would he delete it and be fairplay ? What do you mean ?

**Comment by EyLuismi** [comment]
> > > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> > 
> > 
> > That's correct, but... Why? xD
> 
> Why what ? Why would he delete it and be fairplay ? What do you mean ?

Why would anyone play any differently from France? We like to play in the same conditions, we are good players :smile:

**Review by EyLuismi — CHANGES_REQUESTED** [review]
You have a typo in your commit

**Comment by Piervers** [comment]
> 



> > > > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> > > 
> > > 
> > > That's correct, but... Why? xD
> > 
> > 
> > Why what ? Why would he delete it and be fairplay ? What do you mean ?
> 
> Why would anyone play any differently from France? We like to play in the same conditions, we are good players 😄

Did you read the French script ? It's just an overlay that help us to redraw the drawing by telling us what color to use and where.
But everything is done MANUALLY.
Unlike you, we don't use bots

**Comment by EyLuismi** [comment]
> > 
> 
> > > > > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> > > > 
> > > > 
> > > > That's correct, but... Why? xD
> > > 
> > > 
> > > Why what ? Why would he delete it and be fairplay ? What do you mean ?
> > 
> > 
> > Why would anyone play any differently from France? We like to play in the same conditions, we are good players smile
> 
> Did you read the French script ? It's just an overlay that help us to redraw the drawing by telling us what color to use and where. But everything is done MANUALLY. Unlike you, we don't use bots

Yeah... https://place.luna-park.fr/ `placenlbot.user.js` It's literally a copy from this script xD What are you talking about?

**Comment by Piervers** [comment]
> > > 
> > 
> > 
> > > > > > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> > > > > 
> > > > > 
> > > > > That's correct, but... Why? xD
> > > > 
> > > > 
> > > > Why what ? Why would he delete it and be fairplay ? What do you mean ?
> > > 
> > > 
> > > Why would anyone play any differently from France? We like to play in the same conditions, we are good players smile
> > 
> > 
> > Did you read the French script ? It's just an overlay that help us to redraw the drawing by telling us what color to use and where. But everything is done MANUALLY. Unlike you, we don't use bots
> 
> Yeah... https://place.luna-park.fr/ `placenlbot.user.js` It's literally a copy from this script xD What are you talking about?

Just look at the script that is shared by ALL the french streamers

https://pastebin.com/yf50fdQT
https://github.com/CorentinGC/reddit-place-kcorp/raw/main/kcorp.user.js

Look at the chat if you don't believe me : https://www.twitch.tv/antoinedaniel

If someone want to use the script you shared, right, but it's a minority and NO streamers is telling us to do it

**Comment by nwxz** [comment]
> > > 
> > 
> > 
> > > > > > Still, he is the one who modified it and who make it shareable. If he delet the json, the script will stop working. Easy and simple
> > > > > 
> > > > > 
> > > > > That's correct, but... Why? xD
> > > > 
> > > > 
> > > > Why what ? Why would he delete it and be fairplay ? What do you mean ?
> > > 
> > > 
> > > Why would anyone play any differently from France? We like to play in the same conditions, we are good players smile
> > 
> > 
> > Did you read the French script ? It's just an overlay that help us to redraw the drawing by telling us what color to use and where. But everything is done MANUALLY. Unlike you, we don't use bots
> 
> Yeah... https://place.luna-park.fr/ `placenlbot.user.js` It's literally a copy from this script xD What are you talking about?

Your file litteraly says "Place NL bots", not FR bots, it's not french bots.

Like @Piervers said, you can read french script here : https://github.com/CorentinGC/reddit-place-kcorp

**Pull request closed without merging**
